// IDs are permanent, URL-safe Base62 codes. Add new phrases with a new unused
// two-character ID; do not rename, reuse, or delete an existing key.
export const phrasesById = Object.freeze({
  mF: { text: "30,000-foot view", active: true },
  C0: { text: "An ask", active: true },
  V7: { text: "At-bat", active: true },
  tW: { text: "BAU", active: true },
  JP: { text: "Bandwidth", active: true },
  gR: { text: "Best practices", active: true },
  ER: { text: "Big picture", active: true },
  qB: { text: "Big rock", active: true },
  v8: { text: "Blue sky", active: true },
  Q1: { text: "Boil the ocean", active: true },
  lY: { text: "Build the plane while flying it", active: true },
  "8Z": { text: "Cadence", active: true },
  Yw: { text: "Circle back", active: true },
  "6A": { text: "Clean slate", active: true },
  nr: { text: "Deep dive", active: true },
  NW: { text: "Do more with less", active: true },
  hN: { text: "Dogfooding", active: true },
  Az: { text: "Double-click", active: true },
  bq: { text: "Find a solve", active: true },
  St: { text: "Fire drill", active: true },
  qc: { text: "Get creative", active: true },
  H3: { text: "Get out in front of", active: true },
  k4: { text: "Give you time back", active: true },
  "7g": { text: "Greenfield", active: true },
  eS: { text: "GTM", active: true },
  O5: { text: "Hardening", active: true },
  xD: { text: "High-level", active: true },
  DB: { text: "Ideate", active: true },
  X8: { text: "Is the juice worth the squeeze?", active: true },
  "5O": { text: "Keep me in the loop", active: true },
  jv: { text: "Land the plane", active: true },
  IA: { text: "Laser focused", active: true },
  tK: { text: "Learnings", active: true },
  Vj: { text: "Leverage", active: true },
  AE: { text: "Low-hanging fruit", active: true },
  pM: { text: "Metrics", active: true },
  Mc: { text: "Move the goalposts", active: true },
  ir: { text: "Move the needle", active: true },
  FV: { text: "Moving forward", active: true },
  bG: { text: "Opportunity", active: true },
  za: { text: "Pushback", active: true },
  LO: { text: "Put out fires", active: true },
  u5: { text: "Rearrange deck chairs on the Titanic", active: true },
  BM: { text: "Resonate", active: true },
  KY: { text: "Rockstar", active: true },
  sE: { text: "Scrappy", active: true },
  UM: { text: "SME", active: true },
  "7E": { text: "Socialize", active: true },
  fM: { text: "SWAG", active: true },
  cl: { text: "Synergy", active: true },
  M2: { text: "Take this offline", active: true },
  Wv: { text: "Thought leader", active: true },
  CS: { text: "Unpack", active: true },
  sD: { text: "What are we solving for?", active: true },
  Rh: { text: "Zoom out", active: true }
});
